### ISSUE TITLE
Shaded jar causing security exception

### ISSUE THREAD

**Issue by raghukiran1224** [ibm-watson-iot/iot-java#112]
I was using the shaded jar with deps for a standalone deployment (not relying on Maven) and was running into runtime errors (See below).

I could fix it by modifying the shade configuration to the following (see the following to get further explanation on this below fix - https://stackoverflow.com/questions/999489/invalid-signature-file-when-attempting-to-run-a-jar):

## Shade configuration FIX
```
<filters>
        <filter>
            <artifact>*:*</artifact>
            <excludes>
                <exclude>META-INF/*.SF</exclude>
                <exclude>META-INF/*.DSA</exclude>
                <exclude>META-INF/*.RSA</exclude>
            </excludes>
        </filter>
    </filters>

```

## ERROR
```
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:347)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:301)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:327)
	at java.util.jar.JarVerifier.update(JarVerifier.java:239)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:459)
	at java.util.jar.JarFile.getInputStream(JarFile.java:526)
	at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:1083)
	at sun.misc.Resource.cachedInputStream(Resource.java:106)
	at sun.misc.Resource.getByteBuffer(Resource.java:189)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:692)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:95)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1184)
	at java.security.AccessController.doPrivileged(AccessController.java:686)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:604)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:850)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:829)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:809)
	at java.lang.J9VMInternals.prepareClassImpl(Native Method)
	at java.lang.J9VMInternals.prepare(J9VMInternals.java:291)
	at java.lang.Class.getMethods(Class.java:1347)
```

**Comment by sathipal** [comment]
Thank you, this issue is fixed though pull request https://github.com/ibm-watson-iot/iot-java/pull/120

**Comment by sathipal** [comment]
Merged the changes, hence closing the issue. Please reopen if you still face the issue.
