### ISSUE TITLE
Use IoT Java Client behinde corporate proxy

### ISSUE THREAD

**Issue by stmaute** [ibm-watson-iot/iot-java#23]
I've started using the Device- and Application Client and encountered following problem.
When I want to connect to the Watson IoT Platform from inside our corporate network with http proxy I get this error:

INFORMATION: main: Connecting client d:q39aun:iotsample-app:00testDevice00 to ssl://q39aun.messaging.internetofthings.ibmcloud.com:8883 (attempt #1)...
MqttException (0) - java.net.UnknownHostException: q39aun.messaging.internetofthings.ibmcloud.com
    at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
    at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: q39aun.messaging.internetofthings.ibmcloud.com
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
    at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
    at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
    at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
    ... 1 more

I've tested to set system wide proxy setting with 

<pre>
 System.setProperty("http.proxyHost", "localhost");
 System.setProperty("http.proxyPort", "xxxx");
</pre>

 and  I also tested it with VM options  -Dhttp.proxyPort=xxxx ...

The ProxySelector always returns "DIRECT" and my proxy settings were ignored.
Any ideas or suggestions?

**Comment by sathipal** [comment]
As per my reading, the HTTP Proxy setting affects only the HTTP connections and not the TCP connections that mqtt uses internally. Thats the reason your connection establishment is skipped the proxy setting.

Have you tried using the SOCKS proxy? 

Can you try the different options present here - http://docs.oracle.com/javase/7/docs/technotes/guides/net/proxies.html?

**Comment by stmaute** [comment]
@sathipal Thanks for the quick answer! Now i understand the problem.
But unfortunately my company only have a http proxy and no SOCKS Proxy.  
So I have to find another solution for my problem!

**Comment by sathipal** [comment]
Closing the issue as its not related to this library.
