### ISSUE TITLE
Investigate NullPointerException when unsubscribe is called from multiple threads

### ISSUE THREAD

**Issue by miketran78727** [ibm-watson-iot/iot-java#42]
java.lang.NullPointerException
        at org.eclipse.paho.client.mqttv3.MqttTopic.validate(MqttTopic.java:147)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.unsubscribe(MqttAsyncClient.java:917)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.unsubscribe(MqttAsyncClient.java:898)
        at com.ibm.iotf.devicemgmt.device.ManagedDevice.unsubscribe(ManagedDevice.java:636)
        at com.ibm.iotf.devicemgmt.device.ManagedDevice$ManagedDeviceClient.unsubscribe(ManagedDevice.java:977)
        at com.ibm.internal.iotf.devicemgmt.handler.DMRequestHandler.clearRequestHandlers(DMRequestHandler.java:239)
        at com.ibm.iotf.devicemgmt.device.ManagedDevice.sendUnmanageRequest(ManagedDevice.java:530)
        at com.ibm.iotcloud.test.jmeter.sampler.dm.FirmwareActions.deleteDevice(FirmwareActions.java:193)
        at com.ibm.iotcloud.test.jmeter.sampler.dm.FirmwareActions.teardownTest(FirmwareActions.java:256)
        at org.apache.jmeter.protocol.java.sampler.JavaSampler.testEnded(JavaSampler.java:292)
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:215)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:436)
        at java.lang.Thread.run(Unknown Source)

**Comment by miketran78727** [comment]
I am working on a patch for this issue.

**Comment by miketran78727** [comment]
I submitted a pull request for this issue: https://github.com/ibm-watson-iot/iot-java/pull/43
