### ISSUE TITLE
com.ibm.iotf.client.app.Status fails due to wrong attribute definitions

### ISSUE THREAD

**Issue by ghost** [ibm-watson-iot/iot-java#46]
Attributes defined in class com.ibm.iotf.client.app.Status do not match what is currently being returned by IoTF and it fails with a NullPointerException. Below a few sample status message that currently fail.

{
        "Action": "Disconnect",
        "Time": "2016-07-14T10:00:45.959Z",
        "ClientAddr": "XXX.XXX.XX.XXX",
        "ClientID": "d:XXXXXX:XXX:XXXXXXXX",
        "Port": 8883,
        "SecureConnection": true,
        "Protocol": "mqtt4-tcp",
        "User": "use-token-auth",
        "ConnectTime": "2016-07-14T09:46:40.688Z",
        "ReadBytes": 27385,
        "ReadMsg": 74,
        "WriteBytes": 607,
        "WriteMsg": 2
}

{
        "Action": "Connect",
        "Time": "2016-07-29T10:08:29.322Z",
        "ClientAddr": "XXX.XXX.XX.XXX",
        "ClientID": "d:XXXXXX:XXXXXXX:XXXXXXXXX",
        "Port": 1883,
        "Secure": false,
        "Protocol": "mqtt3"
}

{
        "Action": "Disconnect",
        "Time": "2016-07-29T10:17:31.335Z",
        "ClientAddr": "XXX.XXX.XX.XXX",
        "ClientID": "d:XXXXXX:XXXXXXX:XXXXXXXXX",
        "Port": 1883,
        "Secure": false,
        "Protocol": "mqtt3",
        "ConnectTime": "2016-07-29T10:08:29.300Z",
        "ReadBytes": 112610,
        "ReadMsg": 549,
        "WriteBytes": 27,
        "WriteMsg": 0
}

**Comment by miketran78727** [comment]
@jtikkala : Could you please provide a stack trace when this happened?

**Comment by ghost** [comment]
@miketran78727 : stack trace attached below

MqttException (0) - java.lang.NullPointerException
        at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:197)
        at java.lang.Thread.run(Thread.java:785)
Caused by: java.lang.NullPointerException
        at com.ibm.iotf.client.app.Status.<init>(Status.java:120)
        at com.ibm.iotf.client.app.DeviceStatus.<init>(DeviceStatus.java:47)
        at com.ibm.iotf.client.app.ApplicationClient.messageArrived(ApplicationClient.java:872)
        at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:475)
        at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:379)
        at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:183)
        ... 1 more

**Comment by miketran78727** [comment]
@jtikkala Thanks.  I submitted a pull request to fix this issue: https://github.com/ibm-watson-iot/iot-java/pull/47

**Comment by sathipal** [comment]
I have merged the code changes, Can you please close the issue?

**Comment by ghost** [comment]
Seems to be fixed now. Thanks!
