### ISSUE TITLE
Not working anymore after TLS 1.0 removel

### ISSUE THREAD

**Issue by romeokienzler** [ibm-watson-iot/iot-java#96]
Hi, the very same code doesn't work anymore since TSL has been removed  as described [here](https://developer.ibm.com/iotplatform/2017/04/18/watson-iot-platform-disabling-tls-1-0/), I'm getthing this error:

> INFO: main: Connecting client a:rwyrty:a2g6k39sl6r5 to ssl://rwyrty.messaging.internetofthings.ibmcloud.com:8883 (attempt #1)...
> MqttException (0) - java.net.SocketException: Connection reset
> 	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
> 	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:690)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.net.SocketException: Connection reset
> 	at java.net.SocketInputStream.read(SocketInputStream.java:209)

This is my pom.xml

> 
> 		<dependency>
> 			<groupId>org.eclipse.paho</groupId>
> 			<artifactId>org.eclipse.paho.client.mqttv3</artifactId>
> 			<version>1.1.1</version>
> 		</dependency>
> 		<dependency>
> 			<groupId>com.ibm.messaging</groupId>
> 			<artifactId>watson-iot</artifactId>
> 			<version>0.2.4</version>
> 		</dependency>

I'm highly confident that the client library cannot cope with the missing TLS 1.0, can you please re-confirm?

Here my code for reference:

```
		Properties props = new Properties();
		props.load(WatsonIoTConnector.class.getResourceAsStream("/ibm_watson_iot_mqtt.properties"));
		ApplicationClient myClient = new ApplicationClient(props);
		myClient.connect();
```

And the properties:

```
## Mandatory fields
id = a2g6k39sl6r5
Organization-ID = rwyrty
Authentication-Method = apikey
API-Key = a-rwyrty-f95d3XXXXX
Authentication-Token = ZHd1&O)_J1&TIXXXXX
```

**Comment by romeokienzler** [comment]
Magically problem disappeared after 2 weeks - so most likely a server side problem.
